### ISSUE TITLE
SL Gateway: need to break out strong-gateway-demo into tutorial

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-gateway#33]
- [x] 1. create api server (notes)
- [x] 2. create api client
- [x] 3. spin up the client app and show it using the api server
- [x] 4. introduce gateway, hook up client app with gateway reverse proxy to api server
  - [x] proxy without protection
  - [x] enforce protection
    - [x] register client and users
      - [x] describe sample-data.json as a precanned for our demo purpose only
    - [x] tweak client to exercise oauth 2 flow
      - [x] fetch access token
      - [x] use token to access api (through gateway)
- [x] 5. talk about QOS/policies
  - [x] rate limiting
  - [x] metrics
    - [x] run gateway with strong-pm (local or remote)
    - [x] use arc to show metrics
  - [x] point to docs for other policies
- [x] 6. choose your datasource for your oauth2 metadata/data
  - [x] datasources.json with mongodb
  - [x] run setupdb.js to create tables for relational db
  - [x] point to docs for other types of datasources

---

- Due before June 10th because @altsang has a video shoot scheduled for that date.
- Connect to https://github.com/strongloop/strong-gateway-demo/pull/1

**Comment by superkhau** [comment]
PR: https://github.com/strongloop/strong-gateway-demo/tree/add-tutorial

**Comment by superkhau** [comment]
- [ ] Rename `oauth-explorer` to `oauth2-playground`
- [ ] Rename `notes-app` to `notes-app-plain`
- [ ] Rename `notes-app-with-gateway` to `notes-app-gateway`

**Comment by kithokit** [comment]
May i know when the tutorial will be available?

We are trying to use the strongloop-gateway but there is no demo/tutorial for us to follow. 
The website said contact sales for beta-version.
Is there difference to get started from the source / beta-version?

We are in a hurry to make a decision whether to use strongloop..

**Comment by altsang** [comment]
Simon should be finishing the gateway demo app within a week.  In the meantime, I believe Dennis @dashby3000 has already reached out to you. Can you please tell us more about your project via email thread that Dennis started with you?

the current source is the beta version however it is recommended to have a guided walk through on its usage

**Comment by superkhau** [comment]
Connect to https://github.com/strongloop/strong-gateway-demo/pull/1

**Comment by chandadharap** [comment]
close after merging branch.
