### ISSUE TITLE
createCredentials() is deprecated

### ISSUE THREAD

**Issue by yagobski** [strongloop/strong-gateway#41]
Hy I have :
slc -v
strongloop v5.0.0 (node v0.12.7)
├── strong-arc@1.8.1 (15814c0)
├── strong-build@2.0.4 (9294f54)
├── strong-deploy@3.0.0 (bee617c)
├── strong-mesh-models@8.0.0 (1b220f7)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.1 (b17cbc0)
├─┬ strong-supervisor@3.0.2 (539c0ce)
│ └── strong-agent@1.6.4
├── generator-loopback@1.11.0 (dec0654)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

I get this error when i start using : node auth-server

createCredentials() is deprecated, use tls.createSecureContext instead
/Users/faouzi/Desktop/ournia/apiGateway/auth-server/node_modules/loopback-boot/lib/executor.js:330
    var match = configVariable.match(DYNAMIC_CONFIG_PARAM);
                               ^

**Comment by yagobski** [comment]
Thanks Raymond but i replaced the file ssl_cert.js buy your fix and still get same problem.

**Comment by raymondfeng** [comment]
Can you find other occurrences of `crypto.createCredentials` in your app and deps? For example, `grep -r crypto.createCredentials *`.

**Comment by yagobski** [comment]
Yes. I found another in this file

apiGateway/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Connection.js

line 310 :

 var credentials = Crypto.createCredentials({
      key        : this.config.ssl.key,
      cert       : this.config.ssl.cert,
      passphrase : this.config.ssl.passphrase,
      ca         : this.config.ssl.ca
    });

2015-08-31 22:55 GMT+02:00 Raymond Feng <notifications@github.com>:

**Comment by raymondfeng** [comment]
You probably need to open an issue against node-mysql project.

**Comment by yagobski** [comment]
Thanks i create issue here https://github.com/felixge/node-mysql/issues/1203

**Comment by dougwilson** [comment]
Please do not direct users to grep their code; start the node program with the --trace-deprecation switch instead to determine cause.

**Comment by raymondfeng** [comment]
@dougwilson Nice tip!

**Comment by dougwilson** [comment]
Oh, and hi @raymondfeng ! :) Sorry, I wrote that on a phone, so didn't come through as nice as I liked :) The `mysql` library gets these issues periodically because people just grep and they see the Node.js 0.6/0.8/0.10 compatibility code, even though it's not actually running when they get the message :/

**Comment by raymondfeng** [comment]
@dougwilson Making sense.

**Comment by yagobski** [comment]
I don't get deprecated warning i just get this error now : 

node --trace-deprecation auth-server/

/apiGateway/auth-server/node_modules/loopback-boot/lib/executor.js:330
    var match = configVariable.match(DYNAMIC_CONFIG_PARAM);
